In [1]:
#Ignore warnings
import warnings
warnings.filterwarnings('ignore')
from tensorflow import keras
model = keras.models.load_model("LSTMRNN_Model1.h5")

In [2]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 700, 100)          21901300  
_________________________________________________________________
dropout (Dropout)            (None, 700, 100)          0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 128)               117248    
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 129       
Total params: 22,018,677
Trainable params: 117,377
Non-trainable params: 21,901,300
_________________________________________________________________


In [3]:
#Basic libraries
import pandas as pd 
import numpy as np 

In [4]:
#NLTK libraries
import nltk
import re
import string
from nltk.corpus import stopwords
from wordcloud import WordCloud,STOPWORDS
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
test = pd.read_csv('text_news.csv')

In [8]:
# prepare test data for NN
X_test=test
messages=X_test.copy()
messages.reset_index(inplace=True)
ps =PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print("Status: %s / %s" %(i, len(messages)), end="\r")
    review = re.sub('[^a-zA-Z]', ' ',messages['text'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [9]:
sent_length = max(test['text'], key=len)
print(sent_length)

Verizon Communications’ $4. 83 billion acquisition of Yahoo has the technology cognoscenti scratching their heads. What does Verizon, the country’s biggest wireless company, see in an internet  ? Fortune criticized “The Problem With  . ”  ’s chief executive, John Legere, derided the deal as a “slippery slope. ” The chief executive of Sprint, Marcelo Claure, said that when telecommunications companies try to get into the content business, “history has proven that every single one of them has failed. ” And there are reasons to think history might repeat itself. Yahoo will be merged with AOL, another faded star of Web 1. 0 that Verizon bought last year. These brands from yesterday are supposed to compete for the same advertising dollars that titans like Google and Facebook are devouring faster than ever. Still, there is a surprisingly ambitious, and risky, unifying theme hidden in the oddball assortment of websites and internet services that Verizon has acquired over the last year or so: 

In [11]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [12]:
from tensorflow.keras.preprocessing.text import one_hot
sent_length = 1000
vo_size=500
onehot_rep = [one_hot(words, vo_size) for words in corpus]
embedded_doc=pad_sequences(onehot_rep, padding='pre', maxlen=sent_length)
X_test_final=np.array(embedded_doc)

In [14]:
#Ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [15]:
y_pred_final=model.predict_classes(X_test_final)

In [16]:
from sklearn.metrics import classification_report, accuracy_score

In [17]:
y_pred_final

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1]])

In [19]:
#Ignore warnings
import warnings
warnings.filterwarnings('ignore')
from tensorflow import keras
model2 = keras.models.load_model("Bi-directional_LSTMRNN_Model2.h5")

In [20]:
#Ignore warnings
import warnings
warnings.filterwarnings('ignore')
from tensorflow import keras
model3 = keras.models.load_model("Bi-directional_LSTMRNN_Model3.h5")

In [21]:
#Ignore warnings
import warnings
warnings.filterwarnings('ignore')
from tensorflow import keras
model4 = keras.models.load_model("GRU_RNN_Model4.h5")

In [22]:
model2=model2.predict_classes(X_test_final)

In [23]:
model2

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [24]:
model3=model3.predict_classes(X_test_final)

In [25]:
model3

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1]])

In [26]:
model4=model4.predict_classes(X_test_final)

In [27]:
model4

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1]])